#!/bin/sh
#
# This script is used to enable rudimentary continuous deployment.
#
# It is installed to the production server,
# which holds both a bare, remote copy of this repository
# and a running Docker container of this application.
#
# Adapted from https://stackoverflow.com/a/14453711/4865822.
#
# === Requirements
#
# The production server must have:
#
#   * Ruby (any supported version)
#   * docker-compose (with a docker credential helper on $PATH, if relevant)
#   * pass <https://passwordstore.org>
#   * a Mapbox GL access token at `pass apis/mapbox/access_token`
#
# === Setup
#
#    # ~/.bashrc
#
#    # Only run for interactive shells ==============================================
#    if ! [[ $- =~ i ]]; then
#      export GNUPGHOME="$HOME/.config/gnupg"
#      export PASSWORD_STORE_DIR="$HOME/.config/pass"
#      export PATH="$HOME/.local/bin:$PATH"
#
#      return
#    fi

DEPLOYMENT_DIR="$(mktemp -d)"
GIT_WORK_TREE="$DEPLOYMENT_DIR" git checkout -f

cd "$DEPLOYMENT_DIR"
cp /home/rlue/ryanlue.com/src/sdaqs/data/db_seed.sql "${DEPLOYMENT_DIR}/data" # FIXME

# add server-specific configuration to docker-compose.yml
sed -i -r 's/(\s*)web:/\1  labels:\n\1    traefik.enable: false\n&/' docker-compose.yml
cat <<EOF >> docker-compose.yml
    networks:
      - default
      - router
    labels:
      traefik.http.services.sdaqs.loadbalancer.server.port: 9292
      traefik.http.routers.sdaqs.entrypoints: websecure
      traefik.http.routers.sdaqs.rule: Host(\`airquality.ryanlue.com\`)
      traefik.http.routers.sdaqs.tls: true
      traefik.http.routers.sdaqs.tls.certresolver: letsencrypt
      traefik.docker.network: ryanluecom_default
networks:
  router:
    external:
      name: ryanluecom_default
EOF

MAPBOXGL_ACCESS_TOKEN="$(pass apis/mapbox/access_token)" rake deploy

rm -rf "$DEPLOYMENT_DIR"
