#!/bin/sh
#
# This script is used to enable rudimentary continuous deployment.
#
# It is installed to the production server,
# which holds both a bare, remote copy of this repository
# and a running Docker container of this application.
#
# Adapted from https://stackoverflow.com/a/14453711/4865822.
#
# === Installation
#
# Add the following to the TOP of your production server's .bashrc:
#
#     if ! [[ $- =~ i ]]; then
#       export SDAQS_DEPLOYMENT_DIR="..."
#       export MAPBOXGL_ACCESS_TOKEN=pk.eyJ1...
#       export PATH="$HOME/.local/bin:$PATH"  # or wherever your docker credential provider is stored
#
#       return
#     fi

mkdir "$SDAQS_DEPLOYMENT_DIR" 2>/dev/null
GIT_WORK_TREE="$SDAQS_DEPLOYMENT_DIR" git checkout -f

cd "$SDAQS_DEPLOYMENT_DIR"

# add server-specific configuration to docker-compose.yml
sed -i -r 's/(\s*)web:/\1  labels:\n\1    traefik.enable: false\n&/' docker-compose.yml
cat <<EOF >> docker-compose.yml
    networks:
      - default
      - router
    labels:
      traefik.http.services.sdaqs.loadbalancer.server.port: 9292
      traefik.http.routers.sdaqs.entrypoints: websecure
      traefik.http.routers.sdaqs.rule: Host(\`airquality.ryanlue.com\`)
      traefik.http.routers.sdaqs.tls: true
      traefik.http.routers.sdaqs.tls.certresolver: letsencrypt
      traefik.docker.network: ryanluecom_default
networks:
  router:
    external:
      name: ryanluecom_default
EOF

docker-compose up --detach --build
