# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 99

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented_relative_to_receiver'

Metrics/AbcSize:
  Exclude:
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app.rb'
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'config/**/*'

RSpec/ContextWording:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
