packageExtensions:
  "@ant-design/icons@*":
    peerDependencies:
      react-dom: ^16.12.0
  antd@*:
    dependencies:
      dayjs: ^1.8.18
  rc-animate@*:
    peerDependencies:
      react: ^16.12.0
      react-dom: ^16.12.0
  rc-collapse@*:
    peerDependencies:
      react: ^16.12.0
      react-dom: ^16.12.0
  rc-dialog@*:
    peerDependencies:
      react: ^16.12.0
      react-dom: ^16.12.0
  rc-drawer@*:
    peerDependencies:
      react-dom: ^16.12.0
  rc-field-form@*:
    peerDependencies:
      react-dom: ^16.12.0
  rc-input-number@*:
    peerDependencies:
      react: ^16.12.0
      react-dom: ^16.12.0
  rc-mentions@*:
    peerDependencies:
      react-dom: ^16.12.0
  rc-rate@*:
    peerDependencies:
      react: ^16.12.0
      react-dom: ^16.12.0
  rc-slider@*:
    peerDependencies:
      react: ^16.12.0
      react-dom: ^16.12.0
  rc-tabs@*:
    peerDependencies:
      react-dom: ^16.12.0

yarnPath: .yarn/releases/yarn-rc.js
