version: '3'
services:
  db:
    image: postgis/postgis
    volumes:
      - ./data/db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql:ro
    environment:
      POSTGRES_DB: sdaqs_production
      POSTGRES_PASSWORD: password
    restart: unless-stopped
  web:
    build:
      context: .
      args:
        MAPBOXGL_ACCESS_TOKEN: "${MAPBOXGL_ACCESS_TOKEN}"
    environment:
      APP_DATABASE_URL: postgres://postgres:password@db/sdaqs_production
    ports:
      - 9292:9292
    depends_on:
      - db
    restart: unless-stopped
